language: python
python:
  - '2.7'


# Build on Ubuntu 14.04 .
dist: trusty

# Use the full VM to get all packages.
sudo: true


# Install the "gcc-multilib" package to be able to use 32bit compiler tools on a 64bit VM.
addons:
  apt:
    packages:
    - gcc-multilib
    - lib32z1


# Cache the .mbs folder.
cache:
  directories:
  - $HOME/.mbs


before_install:
  - git submodule update --init --recursive


# Build the flasher artifact, install the required Ivy version and build the flasher_cli artifacts.
script:
  - python2.7 build_artifact.py
