language: python
python:
  - '2.7'


# Build on Ubuntu 14.04 .
dist: trusty

# Use the full VM to get all packages.
sudo: true


# Install the "gcc-multilib" package to be able to use 32bit compiler tools on a 64bit VM.
addons:
  apt:
    packages:
    - gcc-multilib
    - lib32z1


# Cache the .mbs folder.
cache:
  directories:
  - $HOME/.mbs
  - $HOME/.ant/lib


env:
  global:
    - secure: CQaqQBrFIEVHPO+J8gWRCV0eQ2bdwdZG3T8t/DBj7hGTOXqaB1YHSWpSt+xbht/B2pelSz2XOWNhvF8Q9PFqW+nMFANkqz0W24BtBrVhLh6hUh+DLAW9rvctNeKU03Eqke+g7YAex6cLdVqk2HTyUBmMxe/rOGROGj2Sd+auhdc=
    - PATH=/tmp/apache-ant-1.9.6/bin/:$PATH


# The build box uses Ubuntu 12.04, which provides ant 1.8.x . This project
# needs at least ant 1.9.1 to get the "if" attribute (see
# http://ant.apache.org/manual/ifunless.html).
before_install:
  - git submodule update --init --recursive
  - wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.6-bin.tar.bz2 -O /tmp/apache-ant-1.9.6-bin.tar.bz2
  - tar --directory /tmp --extract --bzip2 --file /tmp/apache-ant-1.9.6-bin.tar.bz2


install:
  - pip install -q requests


# Build the flasher artifact, install the required Ivy version and build the flasher_cli artifacts.
script:
  - ./.build.sh


# Deploy the artifacts to BinTray.
after_success:
  - python ivy/deploy.py targets/artifacts_flasher.xml targets/artifacts_flasher_cli.xml


deploy:
  provider: releases
  api_key:
    secure: IBI+iLqQlTzN8RkZ5IokBPYFe7INxXIIHRIxeEFBtAt0r9zXYS122SVTGJUx3xAULEStb+aQ0rs+PSLqWdrptEPyezwAEqKDVDK7n+rjMI2/lvCy0RuSHA1ryp56pCobGpaus7c48EFIC8hfbDvl0BYnymAJwy/FrpntSsvVvd0=
  file:
    - targets/ivy/flasher.zip
    - targets/ivy/ivy.xml
    - targets/ivy/flasher_cli/targets/flasher_cli_windows_amd64.zip
    - targets/ivy/flasher_cli/targets/flasher_cli_windows_x86.zip
  skip_cleanup: true
  on:
    repo: muhkuh-sys/org.muhkuh.tools-flasher
    tags: true
